---
ID: "ba0c56c5-0d37-4ce5-b2f2-b65c98fc35b9"
Parent: "cb2e40c8-e29b-4ef2-8e64-9f793f9fef66"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Hackathon Collection/Hackathon Site/Presentation/Headless Variants/Flexible Container/Default
BranchID: "90e5c519-7479-414f-8cdb-086ea76cc3b7"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{44B913CD-E7B8-4D37-B171-4B1BBBAAA3D2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250308T054434Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\paul.bonilla@verndale.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\paul.bonilla@verndale.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "36af967c-373b-4e9f-ba53-dffc084fb45b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\paul.bonilla@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250308T054434Z
