---
ID: "c63eb25d-c142-446d-9cd8-85107af7464a"
Parent: "91227e7b-b6a1-4750-ab74-172bdf6bd0d5"
Template: "91227e7b-b6a1-4750-ab74-172bdf6bd0d5"
Path: /sitecore/templates/Feature/Content/Rendering Parameters/Flexible Container/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "89474691-0eac-4621-9b8a-44110e520ed6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\raul.villamarin@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240802T174329Z
