---
ID: "b751debe-1af6-48e8-aae6-79006a615dfa"
Parent: "697c6d2c-af3f-4af6-be52-b0dc97c232b9"
Template: "697c6d2c-af3f-4af6-be52-b0dc97c232b9"
Path: /sitecore/templates/Project/Hackathon Collection/Navigation/Rendering Parameters/Footer Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7ec7ce14-4987-4e09-81e6-1f847bce064a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250308T172806Z
