---
ID: "33639cd7-670b-4e10-90fd-85a47679476c"
Parent: "dff3cccd-2113-4710-864b-bb35883b20fb"
Template: "dff3cccd-2113-4710-864b-bb35883b20fb"
Path: /sitecore/templates/Feature/Content/Rendering Parameters/Page Header Structure/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e0a5a812-565b-42b4-a24c-8fad9a96d56a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\paul.bonilla@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240517T164456Z
