---
ID: "712ecd89-f7c5-4b01-a259-2bc98487c898"
Parent: "be01b6fd-c224-4693-a082-972a095c1440"
Template: "be01b6fd-c224-4693-a082-972a095c1440"
Path: /sitecore/templates/Project/Hackathon Collection/Navigation/Rendering Parameters/Header Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "06753548-1795-4435-8d6a-21a9e6a7b0c0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250308T172905Z
